/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package controlAcceso;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Miguel
 */
public class salidaAcceso extends javax.swing.JPanel {

    /**
     * Creates new form salidaAcceso
     */
    public salidaAcceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textoIngresarAcceso = new javax.swing.JLabel();
        fieldCedula = new javax.swing.JTextField();
        textoCedula = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ingresarHora = new com.toedter.components.JSpinField();
        ingresarMinuto = new com.toedter.components.JSpinField();
        textoHora = new javax.swing.JLabel();
        textoMinuto = new javax.swing.JLabel();
        botonIngresarAcceso = new javax.swing.JButton();
        textoFecha = new javax.swing.JLabel();
        elegirFecha = new com.toedter.calendar.JDateChooser();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textoIngresarAcceso.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textoIngresarAcceso.setText("Ingresar Salida");
        jPanel1.add(textoIngresarAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        fieldCedula.setForeground(new java.awt.Color(102, 102, 102));
        fieldCedula.setBorder(null);
        fieldCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fieldCedulaMousePressed(evt);
            }
        });
        fieldCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCedulaActionPerformed(evt);
            }
        });
        jPanel1.add(fieldCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        textoCedula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCedula.setText("Cedula");
        jPanel1.add(textoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(102, 204, 255));
        jSeparator1.setForeground(new java.awt.Color(102, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 190, 30));
        jPanel1.add(ingresarHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 90, -1));
        jPanel1.add(ingresarMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 90, -1));

        textoHora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoHora.setText("Hora");
        jPanel1.add(textoHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, -1, -1));

        textoMinuto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoMinuto.setText("Minuto");
        jPanel1.add(textoMinuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, -1, -1));

        botonIngresarAcceso.setBackground(new java.awt.Color(119, 56, 200));
        botonIngresarAcceso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonIngresarAcceso.setForeground(new java.awt.Color(255, 255, 255));
        botonIngresarAcceso.setText("Ingresar");
        botonIngresarAcceso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonIngresarAcceso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonIngresarAccesoMousePressed(evt);
            }
        });
        botonIngresarAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarAccesoActionPerformed(evt);
            }
        });
        jPanel1.add(botonIngresarAcceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 240, 40));

        textoFecha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoFecha.setText("Fecha");
        jPanel1.add(textoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        elegirFecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elegirFechaMousePressed(evt);
            }
        });
        jPanel1.add(elegirFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldCedulaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fieldCedulaMousePressed

    }//GEN-LAST:event_fieldCedulaMousePressed

    private void fieldCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCedulaActionPerformed

    private void botonIngresarAccesoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonIngresarAccesoMousePressed
     
    }//GEN-LAST:event_botonIngresarAccesoMousePressed

    private void botonIngresarAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarAccesoActionPerformed
      // Obtener los valores de los campos
        String cedula = fieldCedula.getText();
        int hora = ingresarHora.getValue();
        int minuto = ingresarMinuto.getValue();

        // Obtener la fecha del campo elegirFecha
        Date fechaEntrada = elegirFecha.getDate();

        if (fechaEntrada != null) {
            try {
                // Establecer la conexión a la base de datos 
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/bibliotecadb", "root", "123456");

                // Formatear la fecha de entrada como "yyyy-MM-dd"
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
                String fechaEntradaStr = dateFormat.format(fechaEntrada);

                // Preparar la consulta SQL
                String sql = "UPDATE RegistrosAcceso SET HoraSalida = ? WHERE UsuarioID = ? AND Fecha = ?";
                PreparedStatement pstmt = conn.prepareStatement(sql);

                // Establecer los valores de los parámetros
                pstmt.setString(1, hora + ":" + minuto + ":00"); // Crear una cadena de tiempo HH:mm:ss
                pstmt.setString(2, cedula);
                pstmt.setString(3, fechaEntradaStr);

                // Ejecutar la consulta
                pstmt.executeUpdate();

                // Cerrar la conexión
                conn.close();

               
                System.out.println("Salida registrada con éxito.");

            } catch (SQLException e) {
                e.printStackTrace();
               
                System.err.println("Error al registrar salida en la base de datos.");
            }
        } else {
    
            System.err.println("La fecha de entrada no puede ser nula.");
        }
    
    }//GEN-LAST:event_botonIngresarAccesoActionPerformed

    private void elegirFechaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirFechaMousePressed

    }//GEN-LAST:event_elegirFechaMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresarAcceso;
    private com.toedter.calendar.JDateChooser elegirFecha;
    private javax.swing.JTextField fieldCedula;
    private com.toedter.components.JSpinField ingresarHora;
    private com.toedter.components.JSpinField ingresarMinuto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel textoCedula;
    private javax.swing.JLabel textoFecha;
    private javax.swing.JLabel textoHora;
    private javax.swing.JLabel textoIngresarAcceso;
    private javax.swing.JLabel textoMinuto;
    // End of variables declaration//GEN-END:variables
}
