package Principal;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


import conexionDB.conexionDB;
import java.awt.Color;
import javax.swing.ImageIcon;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Miguel
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    menuPrincipal menuPrincipalFrame = new menuPrincipal();
    public Login() {
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        Login = new javax.swing.JLabel();
        Morado = new javax.swing.JPanel();
        IniciarSesion = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        SeparUsuario = new javax.swing.JSeparator();
        textoContraseña = new javax.swing.JLabel();
        SeparContraseña = new javax.swing.JSeparator();
        userPassword = new javax.swing.JPasswordField();
        PanelEntrar = new javax.swing.JPanel();
        Entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(996, 684));

        Login.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/contrasena-de-usuario (2).png"))); // NOI18N
        Login.setText("   LOGIN");

        Morado.setBackground(new java.awt.Color(119, 56, 200));

        javax.swing.GroupLayout MoradoLayout = new javax.swing.GroupLayout(Morado);
        Morado.setLayout(MoradoLayout);
        MoradoLayout.setHorizontalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );
        MoradoLayout.setVerticalGroup(
            MoradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 654, Short.MAX_VALUE)
        );

        IniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 36)); // NOI18N
        IniciarSesion.setText("INICIAR SESIÓN");

        Usuario.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        Usuario.setText("USUARIO");

        userTxt.setFont(new java.awt.Font("Roboto Light", 0, 14)); // NOI18N
        userTxt.setForeground(new java.awt.Color(102, 102, 102));
        userTxt.setText("Ingrese su nombre de usuario");
        userTxt.setBorder(null);
        userTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userTxtMousePressed(evt);
            }
        });
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });

        SeparUsuario.setForeground(new java.awt.Color(0, 0, 0));

        textoContraseña.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        textoContraseña.setText("CONTRASEÑA");

        SeparContraseña.setForeground(new java.awt.Color(0, 0, 0));

        userPassword.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        userPassword.setForeground(new java.awt.Color(102, 102, 102));
        userPassword.setText("********");
        userPassword.setBorder(null);
        userPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userPasswordMousePressed(evt);
            }
        });
        userPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userPasswordActionPerformed(evt);
            }
        });

        PanelEntrar.setBackground(new java.awt.Color(119, 56, 200));

        Entrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        Entrar.setForeground(new java.awt.Color(255, 255, 255));
        Entrar.setText("        ENTRAR");
        Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EntrarMousePressed(evt);
            }
        });

        javax.swing.GroupLayout PanelEntrarLayout = new javax.swing.GroupLayout(PanelEntrar);
        PanelEntrar.setLayout(PanelEntrarLayout);
        PanelEntrarLayout.setHorizontalGroup(
            PanelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEntrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelEntrarLayout.setVerticalGroup(
            PanelEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IniciarSesion)
                    .addComponent(Usuario)
                    .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeparUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textoContraseña)
                    .addComponent(SeparContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addComponent(Morado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Morado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Login)
                .addGap(54, 54, 54)
                .addComponent(IniciarSesion)
                .addGap(48, 48, 48)
                .addComponent(Usuario)
                .addGap(27, 27, 27)
                .addComponent(userTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(textoContraseña)
                .addGap(34, 34, 34)
                .addComponent(userPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeparContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(PanelEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 654));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    private void userPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userPasswordActionPerformed

    private void userTxtMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTxtMousePressed
        // TODO add your handling code here:
          if (userTxt.getText().equals("Ingrese su nombre de usuario")) {
            userTxt.setText("");
            userTxt.setForeground(Color.black);
        }
        if (String.valueOf(userPassword.getPassword()).isEmpty()) {
            userPassword.setText("********");
            userPassword.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userTxtMousePressed

    private void userPasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userPasswordMousePressed
       if (String.valueOf(userPassword.getPassword()).equals("********")) {
            userPassword.setText("");
            userPassword.setForeground(Color.black);
        }
        if (userTxt.getText().isEmpty()) {
            userTxt.setText("Ingrese su nombre de usuario");
            userTxt.setForeground(Color.gray);
        }
    }//GEN-LAST:event_userPasswordMousePressed

    private void EntrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarMousePressed
        // Obtener el nombre de usuario desde el campo de texto
        String usuario = userTxt.getText();
        // Obtener la contraseña como un arreglo de caracteres desde el campo de contraseña
        char[] caracteresContraseña = userPassword.getPassword();
        // Convertir el arreglo de caracteres a una cadena (String)
        String contraseña = new String(caracteresContraseña);
        
        // Llamar a la función autenticar con el nombre de usuario y la contraseña
        if (autenticar(usuario, contraseña)) {
            // Las credenciales son válidas, permitir el acceso
            JOptionPane.showMessageDialog(null, "Ingreso exitoso");
            menuPrincipalFrame.setVisible(true); // Muestra la ventana de menuPrincipal
            this.setVisible(false);
            // Oculta la ventana de Login actual


            // Cierra la ventana actual (Login)
            this.dispose();
        } else {
            // Credenciales inválidas, muestra un mensaje de error
            JOptionPane.showMessageDialog(this, "Credenciales inválidas. Inténtalo de nuevo.");
        }
    }

    private boolean autenticar(String usuario, String contraseña) {
        try {
             // Definir la consulta SQL
            Connection connection = conexionDB.getConnection();
            
            // Definir la consulta SQL parametrizada
            String query = "SELECT * FROM Administradores WHERE Usuario = ? AND Contraseña = ?";
            
             // Crear un PreparedStatement a partir de la conexión y la consulta
            PreparedStatement preparedStatement = connection.prepareStatement(query);
            
             // Establecer el valor del primer parámetro (Usuario) en la consulta
            preparedStatement.setString(1, usuario);
            
            // Establecer el valor del segundo parámetro (Contraseña) en la consulta
            preparedStatement.setString(2, contraseña);
            
            // Ejecutar la consulta y obtener los resultados
            ResultSet resultSet = preparedStatement.executeQuery();

            return resultSet.next(); // Si hay un resultado, las credenciales son válidas
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }
    
    }//GEN-LAST:event_EntrarMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Entrar;
    private javax.swing.JLabel IniciarSesion;
    private javax.swing.JLabel Login;
    private javax.swing.JPanel Morado;
    private javax.swing.JPanel PanelEntrar;
    private javax.swing.JSeparator SeparContraseña;
    private javax.swing.JSeparator SeparUsuario;
    private javax.swing.JLabel Usuario;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel textoContraseña;
    private javax.swing.JPasswordField userPassword;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
