/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Santiago
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackGround = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        TextDescrip = new javax.swing.JLabel();
        TextDescrip2 = new javax.swing.JLabel();
        SubTitulo = new javax.swing.JLabel();
        SalaGeneral = new javax.swing.JLabel();
        FotoSalaGeneral = new javax.swing.JLabel();
        SalaReferencia = new javax.swing.JLabel();
        FotoSalaReferencia = new javax.swing.JLabel();
        FotoSalaInfyJuve = new javax.swing.JLabel();
        SalaInfanyJuvenil = new javax.swing.JLabel();
        bibliocafe = new javax.swing.JLabel();
        FotoBibliocafe = new javax.swing.JLabel();
        SubTitulo2 = new javax.swing.JLabel();
        TextRyC = new javax.swing.JLabel();
        TextRyC2 = new javax.swing.JLabel();
        TextRyC3 = new javax.swing.JLabel();
        FotoLogo = new javax.swing.JLabel();

        Titulo.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        Titulo.setText("Biblioteca Cardenal Darío Castrillón Hoyos de la Universidad Católica de Pereira");

        TextDescrip.setText("La Biblioteca Cardenal Darío Castrillón Hoyos tiene como propósito contribuir al desarrollo académico, intelectual y cultural de la ");

        TextDescrip2.setText("comunidad universitaria y de la región a través de recursos y servicios especializados que promuevan el aprendizaje y la investigación.");

        SubTitulo.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        SubTitulo.setText("NUESTROS ESPACIOS ");

        SalaGeneral.setText("Sala General ");

        FotoSalaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BibliotecaSala.png"))); // NOI18N

        SalaReferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/SalaBiblioteca.jpg"))); // NOI18N

        FotoSalaReferencia.setText("Sala de Referencia");

        FotoSalaInfyJuve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/infantil-5.jpg"))); // NOI18N

        SalaInfanyJuvenil.setText("Sala Infantil y Juvenil");

        bibliocafe.setText("Bibliocafé");

        FotoBibliocafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bibliocafe-2.jpg"))); // NOI18N

        SubTitulo2.setFont(new java.awt.Font("Roboto", 3, 12)); // NOI18N
        SubTitulo2.setText("Registo y control del recinto  ");

        TextRyC.setText("A continuacion se podra Agregar, Editar, y Eliminar nuevos o antiguos visitantes de la Biblioteca Cardenal");

        TextRyC2.setText("Dario Castrillon de la Universidad Catolica de Pereira, llevando acabo un mejor control de los usuarios,");

        TextRyC3.setText("haciendo que sea mas facil para los usuarios, y llevar un conteo de los usuarios.");

        FotoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/LogoUniversidadXbiblioteca.png"))); // NOI18N

        javax.swing.GroupLayout BackGroundLayout = new javax.swing.GroupLayout(BackGround);
        BackGround.setLayout(BackGroundLayout);
        BackGroundLayout.setHorizontalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BackGroundLayout.createSequentialGroup()
                            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BackGroundLayout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(FotoSalaGeneral))
                                .addGroup(BackGroundLayout.createSequentialGroup()
                                    .addGap(78, 78, 78)
                                    .addComponent(SalaGeneral)))
                            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(BackGroundLayout.createSequentialGroup()
                                    .addGap(39, 39, 39)
                                    .addComponent(SalaReferencia)
                                    .addGap(45, 45, 45)
                                    .addComponent(FotoSalaInfyJuve)
                                    .addGap(54, 54, 54))
                                .addGroup(BackGroundLayout.createSequentialGroup()
                                    .addGap(56, 56, 56)
                                    .addComponent(FotoSalaReferencia)
                                    .addGap(76, 76, 76)
                                    .addComponent(SalaInfanyJuvenil)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bibliocafe)
                                    .addGap(42, 42, 42))))
                        .addGroup(BackGroundLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextDescrip2)
                                .addComponent(TextDescrip)
                                .addComponent(FotoBibliocafe, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FotoLogo, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addGroup(BackGroundLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SubTitulo2)
                            .addComponent(TextRyC)
                            .addComponent(TextRyC2)
                            .addComponent(TextRyC3))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        BackGroundLayout.setVerticalGroup(
            BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackGroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(TextDescrip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextDescrip2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SubTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaGeneral)
                    .addComponent(FotoSalaReferencia)
                    .addComponent(SalaInfanyJuvenil)
                    .addComponent(bibliocafe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BackGroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FotoSalaGeneral)
                    .addComponent(SalaReferencia)
                    .addComponent(FotoSalaInfyJuve)
                    .addComponent(FotoBibliocafe))
                .addGap(27, 27, 27)
                .addComponent(SubTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextRyC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextRyC2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextRyC3)
                .addGap(41, 41, 41)
                .addComponent(FotoLogo)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackGround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGround;
    private javax.swing.JLabel FotoBibliocafe;
    private javax.swing.JLabel FotoLogo;
    private javax.swing.JLabel FotoSalaGeneral;
    private javax.swing.JLabel FotoSalaInfyJuve;
    private javax.swing.JLabel FotoSalaReferencia;
    private javax.swing.JLabel SalaGeneral;
    private javax.swing.JLabel SalaInfanyJuvenil;
    private javax.swing.JLabel SalaReferencia;
    private javax.swing.JLabel SubTitulo;
    private javax.swing.JLabel SubTitulo2;
    private javax.swing.JLabel TextDescrip;
    private javax.swing.JLabel TextDescrip2;
    private javax.swing.JLabel TextRyC;
    private javax.swing.JLabel TextRyC2;
    private javax.swing.JLabel TextRyC3;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel bibliocafe;
    // End of variables declaration//GEN-END:variables
}
